In [1]:
import numpy as np

sales = np.array([
[10, 12, 11, 15, 20, 18, 19],
[ 5, 7, 6, 8, 10, 9, 12],
[30, 28, 35, 40, 38, 36, 42],
[14, 13, 15, 16, 18, 17, 20],
[22, 25, 24, 23, 26, 28, 30]
])

print("Read the sales")

Read the sales


In [2]:
products = np.array(["Phone", "Laptop", "Shoes", "Watch", "Headphones"])
print("Read the products")

Read the products


In [3]:
days = np.array(["Mon","Tue","Wed","Thu","Fri","Sat","Sun"])
print("Read the days")

Read the days


In [20]:
# 4) NumPy Interview Question Set (Complete Coverage)

# 4.1 Basics

# 1. Print sales.shape, sales.ndim, sales.dtype

sales.shape
sales.ndim
sales.dtype

(5, 7)

In [21]:
# 2. Create zeros and ones array of shape (5,7)

zeros_arr = np.zeros((5,7))
zeros_arr

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [12]:
# 2. Create ones array of shape (5,7)

import numpy as np

ones_arr = np.ones((5, 7))
print(ones_arr)

[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


In [15]:
#Generic syntax to fill with specific number

threes = np.full((5, 7), 3)
print(threes)

[[3 3 3 3 3 3 3]
 [3 3 3 3 3 3 3]
 [3 3 3 3 3 3 3]
 [3 3 3 3 3 3 3]
 [3 3 3 3 3 3 3]]


In [17]:
# 4.2 Indexing & Slicing

# 1. Get sales of Shoes for all days

sales[2]



array([30, 28, 35, 40, 38, 36, 42])

In [18]:
# or

shoe_index = np.where(products == "Shoes")[0][0]
sales[shoe_index]

array([30, 28, 35, 40, 38, 36, 42])

In [19]:
# 2. Get sales for Friday for all products

sales[:,2]

array([11,  6, 35, 15, 24])

In [22]:
# or

fri_index = np.where(days == "Fri")[0][0]
sales[:, fri_index]

array([20, 10, 38, 18, 26])

In [30]:
# 3. Get first 3 products and first 3 days

sales[0:3,0:3]

array([[10, 12, 11],
       [ 5,  7,  6],
       [30, 28, 35]])

In [31]:
# 4.3 Aggregations

# 1. Total weekly sales per product (row sum)

np.sum(sales,axis =1)

array([105,  57, 249, 113, 178])

In [32]:
# 2. Total sales per day (column sum)

np.sum(sales,axis = 0)

array([ 81,  85,  91, 102, 112, 108, 123])

In [33]:
# 3. Find max sales value and its index position

np.max(sales)

np.int64(42)

In [35]:
max_value = np.max(sales)
pposition = np.unravel_index(np.argmax(sales),sales.shape)

print(max_value)
print(position)

42
(np.int64(2), np.int64(6))


In [39]:
# 4. Mean sales per product

np.mean(sales,axis=1)
np.round(np.mean(sales,axis=1),2)

array([15.  ,  8.14, 35.57, 16.14, 25.43])

In [40]:
# 4.4 Reshape / Flatten

# 1. Flatten the matrix to 1D

sales.flatten()

array([10, 12, 11, 15, 20, 18, 19,  5,  7,  6,  8, 10,  9, 12, 30, 28, 35,
       40, 38, 36, 42, 14, 13, 15, 16, 18, 17, 20, 22, 25, 24, 23, 26, 28,
       30])

In [42]:
# 2. Reshape into (7,5) and explain what it represents

sales_reshaped = sales.reshape(7,5)
sales_reshaped

array([[10, 12, 11, 15, 20],
       [18, 19,  5,  7,  6],
       [ 8, 10,  9, 12, 30],
       [28, 35, 40, 38, 36],
       [42, 14, 13, 15, 16],
       [18, 17, 20, 22, 25],
       [24, 23, 26, 28, 30]])

In [44]:
# 4.5 np.where + conditions

# 1. Replace all values < 10 with 10

updated_sales = np.where(sales < 10, 10, sales)
updated_sales

array([[10, 12, 11, 15, 20, 18, 19],
       [10, 10, 10, 10, 10, 10, 12],
       [30, 28, 35, 40, 38, 36, 42],
       [14, 13, 15, 16, 18, 17, 20],
       [22, 25, 24, 23, 26, 28, 30]])

In [45]:
# 2. Find indices where sales > 35

sales_indices = np.where(sales>35)
sales_indices

(array([2, 2, 2, 2]), array([3, 4, 5, 6]))

In [51]:
# 4.6 Random + Simulation

# 1. Generate random noise matrix (5x7) and add it to sales

# Generate random noise (5x7)
noise = np.random.randn(5, 7)

# Add noise to sales
sales_with_noise = sales + noise

np.round((sales_with_noise),2)

array([[ 9.83, 13.11, 10.25, 16.12, 18.54, 17.06, 18.52],
       [ 5.85,  8.22,  5.87,  8.37,  9.46,  9.54, 13.35],
       [30.16, 28.54, 37.39, 39.74, 36.37, 35.93, 42.31],
       [13.4 , 14.37, 16.8 , 17.92, 16.47, 16.12, 19.68],
       [21.64, 21.95, 24.13, 22.76, 28.  , 27.31, 30.88]])

In [53]:
# 2. Generate random ratings between 1 and 5 for 10 customers

rating = np.random.randint(1,6,10)
rating

array([1, 4, 2, 2, 1, 2, 4, 2, 3, 1], dtype=int32)

In [63]:
# 4.7 Linear Algebra (Basic)

# 1. Compute dot product of total sales per product with weights

# total sales per product (row-wise sum)
total_sales = np.sum(sales, axis=1)

# example weights (must be length 5)
weights = np.array([0.2, 0.1, 0.3, 0.15, 0.25])

# dot product
result = np.dot(total_sales, weights)
result
round((result),2)

np.float64(162.85)

In [66]:
# 2. Normalize sales using min-max scaling

# Min-Max Normalization
normalized_sales = (sales - sales.min()) / (sales.max() - sales.min())

np.round((normalized_sales),2)

array([[0.14, 0.19, 0.16, 0.27, 0.41, 0.35, 0.38],
       [0.  , 0.05, 0.03, 0.08, 0.14, 0.11, 0.19],
       [0.68, 0.62, 0.81, 0.95, 0.89, 0.84, 1.  ],
       [0.24, 0.22, 0.27, 0.3 , 0.35, 0.32, 0.41],
       [0.46, 0.54, 0.51, 0.49, 0.57, 0.62, 0.68]])

In [ ]:
######END#####